In [1]:
import gymnasium as gym
import torch

env = gym.make("CarRacing-v2")

In [2]:
obs, _ = env.reset()
obs.shape

(96, 96, 3)

In [3]:
env.action_space.shape

(3,)

In [4]:
from ppo.network import CNNValue, CNNPolicy

value = CNNValue(in_shape=(3, 96, 96))
policy = CNNPolicy(in_shape=(3, 96, 96), out_size=env.action_space.shape[0])
obs_tensor = torch.tensor(obs).permute(2, 0, 1).unsqueeze(0)

In [5]:
value(obs_tensor)

tensor([[0.2321]], grad_fn=<AddmmBackward0>)

In [6]:
act, logp, mean = policy(obs_tensor)
act, logp, mean

(tensor([[-1.0964, -0.9216,  0.8428]]),
 tensor([-3.8505], grad_fn=<SumBackward1>),
 tensor([[-0.1686, -0.3435, -0.0018]], grad_fn=<AddmmBackward0>))

In [7]:
policy(obs_tensor, act)

tensor([[-1.5889, -0.8731, -1.3884]], grad_fn=<SubBackward0>)

In [8]:
print(value)
print(policy)

CNNValue(
  (layers): Sequential(
    (0): CNN(
      (conv): Sequential(
        (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
        (1): ReLU()
        (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
        (3): ReLU()
        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
        (5): Flatten(start_dim=1, end_dim=-1)
        (6): ReLU()
      )
      (fc): Linear(in_features=4096, out_features=256, bias=True)
    )
    (1): ReLU()
    (2): Linear(in_features=256, out_features=1, bias=True)
  )
)
CNNPolicy(
  (layers): Sequential(
    (0): CNN(
      (conv): Sequential(
        (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
        (1): ReLU()
        (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
        (3): ReLU()
        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
        (5): Flatten(start_dim=1, end_dim=-1)
        (6): ReLU()
      )
      (fc): Linear(in_features=4096, out_features=256, bias=True)
    )
    (1): ReLU()
    (